### ISSUE TITLE
Percentage transparency of the guide-note

### ISSUE THREAD

**Issue by Hellcarttt** [sevenc-nanashi/MikuMikuWorld4CC#43] opened 2024-08-01 22:58 UTC
I know that it may be problematic to implement this, but to optimise some charts (and my ideas) it is necessary. Leave Ease In/ Ease Out and in addition to them in the "No Disappearance" mode, make a transparency parameter (1%/5%/10%/15%...)

**Comment by mikreo** [comment] 2024-08-01 23:02
Duplicate of #9 and #15.

**Closed by mikreo** 2024-08-01 23:02 UTC
